PROCESS_DIRECTORY: 'process_C3_short'
REQUESTED_FILES: []
REQUESTED_TAGS: [
  'phenotype.csv',
  'cells.csv',
  'annotate_SBS.tif',
  'annotate_segment.tif',
  'phenotype_aligned.tif',
]
# discarded after processing to save space
TEMP_TAGS: ['maxed.tif', 'peaks.tif', 'std.tif']

### INPUT TO ANALYSIS
INPUT_DIRECTORY: 'input'
# WELL_TILE_LIST: 'tiles_C3.csv'
WELL_TILE_LIST: 'tiles_C3_short.csv'

BARCODE_TABLE: 'barcodes.csv'
MAGNIFICATION: '20X'
SBS_CYCLES: [1, 2, 3] # cycles to include for analysis
SBS_CYCLE_FORMAT: 'c{cycle}-SBS-{cycle}' # python format string
PHENOTYPE_CYCLE: 'c0-DAPI-GFP-RFP'

### ANALYSIS PARAMETERS
NUCLEUS_AREA: [40, 400] # min and max nucleus area in pixels
THRESHOLD_DAPI: 1000  # threshold for segmenting nuclei
THRESHOLD_CELL: 600  # threshold for segmenting cells
THRESHOLD_READS: 150  # threshold for detecting reads
NUCLEUS_PHENOTYPE_FEATURES: [
    'label', # required to join SBS and phenotype data
    'i', 'j', 'area', 
    ['c0_mean', 'dapi_mean'],
    ['c1_mean', 'gfp_mean'],
    ['c2_mean', 'rfp_mean'],
    ['c0_median', 'dapi_median'],
    ['c1_median', 'gfp_median'],
    ['c2_median', 'rfp_median'],
    ['c0_max', 'dapi_max'],
    ['c1_max', 'gfp_max'],
    ['c2_max', 'rfp_max'],
    ['c0_min', 'dapi_min'],
    ['c1_min', 'gfp_min'],
    ['c2_min', 'rfp_min'],
    ['c0c1_corr', 'dapi_gfp_corr'],
    ['c0c2_corr', 'dapi_rfp_corr'],
    ['c1c2_corr', 'gfp_rfp_corr'],
  ]
CELL_PHENOTYPE_FEATURES: [
  'label', 'area',
    ['c1_mean', 'gfp_mean'],
    ['c2_mean', 'rfp_mean'],
    ['c1_median', 'gfp_median'],
    ['c2_median', 'rfp_median'],
    ['c1_max', 'gfp_max'],
    ['c2_max', 'rfp_max'],
    ['c1c2_corr', 'gfp_rfp_corr'],
]

### DISPLAY OPTIONS
DISPLAY_RANGES:
  DAPI: [500, 15000]
  SBS_G: [100, 5000]
  SBS_T: [100, 4000]
  SBS_A: [100, 8000]
  SBS_C: [100, 2300]
LUTS:
  DAPI: 'GRAY'
  SBS_G: 'GREEN'
  SBS_T: 'RED'
  SBS_A: 'MAGENTA'
  SBS_C: 'CYAN'


# NEW FIELDS
INCLUDE_WELLS_TILES: 'all'
MODE: 'process'
SBS_INPUT_TAG: 'tif'
PHENOTYPE_INPUT_TAG: 'tif'
MAXED_WIDTH: 5

SEGMENT_METHOD: 'cellpose'
CELLPOSE_CYTO_CHANNEL: 4 # 0-indexed, 4="C" channel from sequencing
CELLPOSE_DIAMETER: 22
AUTOSCALE_PHENOTYPE: True