PROCESS_DIRECTORY: 'process_C3'
REQUESTED_FILES: []
REQUESTED_TAGS: [
  # 'phenotype_aligned.tif',
  'cells.csv',
  'annotate_SBS.tif',
  # 'phenotype.csv',
  # 'annotate_SBS_extra.tif',
]
# discarded after processing to save space
TEMP_TAGS: ['maxed.tif', 'peaks.tif', 'std.tif']
# TEMP_TAGS: [] 

### INPUT TO ANALYSIS
INPUT_DIRECTORY: 'input'
WELL_TILE_LIST: 'tiles_C3.csv'

BARCODE_TABLE: 'barcodes.csv'
MAGNIFICATION: '20X'
SBS_CYCLES: [1, 2, 3] # cycles to include for analysis
SBS_CYCLE_FORMAT: 'c{cycle}-SBS-{cycle}' # python format string
PHENOTYPE_CYCLE: 'c0-DAPI-GFP-RFP'

### ANALYSIS PARAMETERS
NUCLEUS_AREA: [40, 400] # min and max nucleus area in pixels
THRESHOLD_DAPI: 1000  # threshold for segmenting nuclei
THRESHOLD_CELL: 600  # threshold for segmenting cells
THRESHOLD_READS: 150  # threshold for detecting reads
NUCLEUS_PHENOTYPE_FEATURES: [
    'label', # required to join SBS and phenotype data
    'i', 'j', 'area', 
    'dapi_gfp_corr', 
    'dapi_max', 'dapi_mean', 'dapi_median',
    'gfp_max', 'gfp_mean', 'gfp_median',
  ]
CELL_PHENOTYPE_FEATURES: ['label', 'area']

### DISPLAY OPTIONS
DISPLAY_RANGES:
  DAPI: [500, 15000]
  SBS_G: [100, 5000]
  SBS_T: [100, 4000]
  SBS_A: [100, 8000]
  SBS_C: [100, 2300]
LUTS:
  DAPI: 'GRAY'
  SBS_G: 'GREEN'
  SBS_T: 'RED'
  SBS_A: 'MAGENTA'
  SBS_C: 'CYAN'


# NEW FIELDS
INCLUDE_WELLS_TILES: 'all'
MODE: 'process'
SBS_INPUT_TAG: 'tif'
PHENOTYPE_INPUT_TAG: 'tif'
MAXED_WIDTH: 5

NUCLEAR_SEGMENT: 'cell_2019'
NUCLEAR_SEGMENT: 'cellpose'