# https://www.sichong.site/2020/02/25/snakemake-and-slurm-how-to-manage-workflow-with-resource-constraint-on-hpc/
# fancier: https://github.com/Snakemake-Profiles/slurm
jobs: 100
cluster: "sbatch 
  -p {params.partition} 
  --gres=gpu:{resources.gpus}
  --mem={resources.mem_gb}g 
  -c {resources.cpus} 
  -t {resources.time_min} 
  -o logs/slurm/{rule}_{wildcards} 
  -e logs/slurm/{rule}_{wildcards}
  "
default-resources: [cpus=1, gpus=0, mem_gb=2, time_min=60] # per job
resources: [cpus=100, gpus=6, mem_gb=500] # max resources over concurrent jobs
latency-wait: 45 # wait for distributed file system
