cluster: sbatch
jobs: 100
use-conda: true
cluster: "sbatch -p short --mem={resources.mem_mb} -c {resources.cpus} -o logs_slurm/{rule}_{wildcards} -e logs_slurm/{rule}_{wildcards}"
default-resources: [cpus=1, mem_mb=2000]
resources: [cpus=100, mem_mb=200000]
